version: '3.1'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: resource
      POSTGRES_USER: resource
      POSTGRES_PASSWORD: resource
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U resource -d resource"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    restart: always
    environment:
      - DB_HOST=postgres
      - DB_USER=resource
      - DB_PASSWORD=resource
      - DB_NAME=resource
      - DB_PORT=5432
      - PORT=8080
      - NODE_ENV=production
      - LOG_LEVEL=info
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npm run migrate && npm run seed && npm start"

volumes:
  postgres-data: